### ISSUE TITLE
Does not work with free account

### ISSUE THREAD

**Issue by kasimodem** [walterl/proton-privoxy#1]
Hi,

Thanks for your work.
I would like to submit a bug.

When I choose 1 (free) as Tier, it still try to connect to a non free server so it says invalid account.
Solution was to change the variable PVPN_CMD_ARGS to "connect name_of_a_free_server" and it worked.

Free servers are here : https://protonvpn.com/vpn-servers
They are marked with a F

As today, the free servers are :
nl-free-01
nl-free-02
nl-free-03
jp-free-01
jp-free-02
jp-free-03
us-free-01
us-free-02
us-free-03

So, as I'm in Europe, I forced the command connect nl-free-01 and it worked.
Maybe you should change the connection script to restrict access to those 9 servers when we choose Tier 1.

Thanks.

**Comment by JaySee3** [comment]
Try using 0 (zero) instead of 1. I think the documentation might be incorrect.

**Comment by walterl** [comment]
I honestly haven't tested/used this with the free accounts, and I'm not sure when I'll get around to doing so. PR's welcome 😉.
