### ISSUE TITLE
Fail on Raspberry Pi

### ISSUE THREAD

**Issue by igorkulman** [walterl/proton-privoxy#10]
Trying to run the container on Raspberry Pi I am getting

```
standard_init_linux.go:228: exec user process caused: exec format error
```

**Comment by Railline** [comment]
you have try to run amd64 (Intel) prog on arm64 (raspberry)

**Comment by walterl** [comment]
We now have [ARM builds](https://hub.docker.com/repository/registry-1.docker.io/walt3rl/proton-privoxy/tags?page=1&ordering=last_updated).
