### ISSUE TITLE
Doesnt seem to work

### ISSUE THREAD

**Issue by mrkia84** [walterl/proton-privoxy#12]
After some trial and error getting setup in the first place I still dont see it work. 

root@SERVERNAME ~# docker container run -d \
> --device=/dev/net/tun --cap-add=NET_ADMIN \
> -v /etc/localtime:/etc/localtime:ro \
> -p 8888:8080 \
> -e PVPN_USERNAME=*#*#*#*#*#*#*#*#*#*#*#*#*# \
> -e PVPN_PASSWORD=*#*#*#*#*#*#*#*#*#*#*#*#*# \
> -e PVPN_TIER=3 -e HOST_NETWORK=10.0.0.0/8 \
> -e PVPN_CMD_ARGS="sc" \
> --name proton-privoxy walt3rl/proton-privoxy
04358e68bc32d9336acb1dfa170deb4d005fab217628ce954ec3b0fe77d088ad

root@SERVERNAME ~# curl --proxy http://127.0.0.1:8888 --insecure https://ipinfo.io/ip
curl: (56) Recv failure: Connection reset by peer
root@SERVERNAME ~# curl --proxy http://127.0.0.1:8888 --insecure http://ipinfo.io/ip
curl: (52) Empty reply from server
root@SERVERNAME ~# curl --proxy http://127.0.0.1:8888 http://ipinfo.io/ip
curl: (52) Empty reply from server
root@SERVERNAME ~# curl --proxy http://127.0.0.1:8888 https://ipinfo.io/ip
curl: (56) Proxy CONNECT aborted
root@SERVERNAME ~# curl --proxy https://127.0.0.1:8888 https://ipinfo.io/ip
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to 127.0.0.1:8888 

root@SERVERNAME ~# curl https://ipinfo.io/ip
##.###.###.##

root@SERVERNAME ~# curl --proxy https://127.0.0.1:8888 https://ipinfo.io/ip
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to 127.0.0.1:8888 
root@SERVERNAME ~# curl --proxy http://127.0.0.1:8888 https://ipinfo.io/ip
curl: (56) Proxy CONNECT aborted
root@SERVERNAME ~# curl --proxy http://127.0.0.1:8888 --insecure https://ipinfo.io/ip
curl: (56) Proxy CONNECT aborted

root@SERVERNAME ~# docker container ls
CONTAINER ID        IMAGE                    COMMAND             CREATED              STATUS              PORTS                    NAMES
04358e68bc32        walt3rl/proton-privoxy   "runsvdir /app"     About a minute ago   Up About a minute   0.0.0.0:8888->8080/tcp   proton-privoxy

root@SERVERNAME /# curl --proxy http://127.0.0.1:8888 --insecure https://ipinfo.io/ip
curl: (56) Proxy CONNECT aborted

**Comment by mrkia84** [comment]
got this from the docker log. something broken perhaps?

Device "proton0" does not exist.
Failed to bring up VPN :(
[!] There was an error connecting to the ProtonVPN API.
[!] Please make sure your connection is working properly!
Usage:
    protonvpn init
    protonvpn (c | connect) [<servername>] [-p <protocol>]
    protonvpn (c | connect) [-f | --fastest] [-p <protocol>]
    protonvpn (c | connect) [--cc <code>] [-p <protocol>]
    protonvpn (c | connect) [--sc] [-p <protocol>]
    protonvpn (c | connect) [--p2p] [-p <protocol>]
    protonvpn (c | connect) [--tor] [-p <protocol>]
    protonvpn (c | connect) [-r | --random] [-p <protocol>]
    protonvpn (r | reconnect)
    protonvpn (d | disconnect)
    protonvpn (s | status)
    protonvpn configure
    protonvpn refresh
    protonvpn examples
    protonvpn (-h | --help)
    protonvpn (-v | --version)

**Comment by walterl** [comment]
Your `PVPN_CMD_ARGS="sc"` is probably the issue. It should contain all arguments to `protonvpn`, including the command, meaning it should probably be `PVPN_CMD_ARGS="connect --sc"`

**Comment by mrkia84** [comment]
That worked! Thank you!

root@SERVERNAME ~# docker logs b56c35a71eb6
Connecting to IS-US#1 via UDP...
Connected!
2021-08-30 15:53:18.232 7fb85c15bb48 Info: Privoxy version 3.0.32
2021-08-30 15:53:18.232 7fb85c15bb48 Info: Program name: privoxy
2021-08-30 15:53:18.244 7fb85c15bb48 Info: Listening on port 8080 on IP address 0.0.0.0
root@SERVERNAME ~# curl --proxy http://127.0.0.1:8888 https://ipinfo.io/ip 
###.###.###.### (WORKING)
