### ISSUE TITLE
Running from windows: command line question

### ISSUE THREAD

**Issue by MrVhek** [walterl/proton-privoxy#23]
Hi !
Can you please explain these lines on the docker run configuration ?
--device=/dev/net/tun --cap-add=NET_ADMIN \
-v /etc/localtime:/etc/localtime:ro \

I'm trying to start it from windows but I don't have a volume /etc/localtime and it doesn't seems to work...
Thanks

**Comment by MrVhek** [comment]
Ok I've tried initially in git bash but git bash doesn't recognize --device=/dev/net/tun, --cap-add=NET_ADMIN is to add capabilities for managing network for what I saw. So I launched it without the volume and in powershell and it works.

**Comment by walterl** [comment]
I've never used Docker on Windows, so could help. Thanks for reporting back. :star:
