### ISSUE TITLE
I already have a working Privoxy...

### ISSUE THREAD

**Issue by vladns** [walterl/proton-privoxy#28]
Privoxy is already running on my router as a filtering web proxy. I don't quite understand why Privoxy is here? Is it possible to configure Privoxy in this configuration so that only some sites could be connected to the vpn using Privoxy commands? I mean like this
`{+forward-override{forward 127.0.0.1:8888}}`
`site.com/`

**Comment by walterl** [comment]
> "I don't quite understand why Privoxy is here?"

One of the main motivations for this project was to allow users to run multiple ProtonVPN connections simultaneously, and allowing different applications to use specific connections. That is why the ProtonVPN connections are "isolated" in a Docker container. But we still need a way to utilize this connection from the host, and Privoxy was the simplest solution that I could think of. And you get some basic privacy filtering for free! :slightly_smiling_face: 

> "Is it possible to configure Privoxy in this configuration so that only some sites could be connected to the vpn using Privoxy commands?"

I haven't tried that yet, but I would expect you to be able to simply Docker-mount your own Privoxy config over the default one:

    docker run -v /etc/privoxy/config:/app/proton-privoxy/config ...
