### ISSUE TITLE
Oracle cloud vps

### ISSUE THREAD

**Issue by Merendino1234** [walterl/proton-privoxy#29]
Hi, I'm using oracle cloud free vps to host the proxy it works locally but not from my pc even with open ports could you help me? 

![image](https://user-images.githubusercontent.com/78469030/216776480-30856a7d-bc61-42e7-a8c1-4bd1419c5489.png)

**Comment by walterl** [comment]
My first guess would be that a firewall is blocking the traffic somewhere along the way. If you've opened up your cloud instance's port 8888 as you've said, then it's probably the firewall running on that instance itself.

Closing this issue, as such networking troubleshooting is not an issue with proton-privoxy.
