### ISSUE TITLE
runsv proton-privoxy: fatal: unable to start ./run: file does not exist

### ISSUE THREAD

**Issue by Puncia** [walterl/proton-privoxy#31]
On Windows 11,
I've followed the instructions, cloned the repo, then `docker build -t walt3rl/proton-privoxy .`

once built, I run `docker run -d --device=/dev/net/tun --cap-add=NET_ADMIN -v /etc/localtime:/etc/localtime:ro -p 8888:8080 -e PVPN_USERNAME=<user> -e PVPN_PASSWORD=<password> -e PVPN_TIER=0 --name proton-privoxy walt3rl/proton-privoxy`, populating the variables appropriately, but I'm getting `runsv proton-privoxy: fatal: unable to start ./run: file does not exist` in the console.

What's happening?

![image](https://user-images.githubusercontent.com/4633311/229817065-5abde5c4-4e99-44e2-b962-3c50ee1bbbe9.png)

**Comment by walterl** [comment]
I don't have any experience with Docker on Windows, so unfortunately I can't be of much help.

**Comment by 100WarningsButWorks** [comment]
Convert all line ending from CRLF to LF. Use dos2unix. Worked like a charm.

https://dos2unix.sourceforge.io/#DOS2UNIX

**Comment by walterl** [comment]
Thanks, @100WarningsButWorks.
