### ISSUE TITLE
The proxy server is refusing connections

### ISSUE THREAD

**Issue by B0G0311** [walterl/proton-privoxy#32]
I setup proton-privoxy in a docker-compose stack to mainly work alongside my qbittorrent and prowlarr containers yet, it does not seem to be allowing connections.  My output for '$ curl --proxy http://127.0.0.1:8888 https://ipinfo.io/ip' shows an ip address and appears to be working. The problem presents itself when I connect to proxy to qbittorrent through the proxy server setting in the interface but instead it shows the firewalled connection status and no upload or download goes through the container.

My docker-compose.yml 
`version: "3"

services:
  proton-privoxy:
    image: walt3rl/proton-privoxy
    container_name: proton-privoxy
    environment:
      - PVPN_USERNAME=${PVPN_USERNAME}
      - PVPN_PASSWORD=${PVPN_PASSWORD}
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8888:8080
    restart: unless-stopped
    devices:
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - proton-connect

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./prowlarr:/config
    ports:
      - 9696:9696
    networks:
      - proxy
      - proton-connect
    labels:
      - "traefik.docker.network=proxy"
      - "traefik.enable=true"
      - "traefik.http.routers.prowlarr.entrypoints=https"
      - "traefik.http.routers.prowlarr.rule=Host(`${TRAEFIK_PROWLARR}`)"
      - "traefik.http.routers.prowlarr.tls=true"
      - "traefik.http.routers.prowlarr.tls.certresolver=mydnschallenge"
      # Watchtower Update
      - "com.centurylinklabs.watchtower.enable=true"
      # Ip filtering
      #- "traefik.http.routers.prowlarr.middlewares=whitelist@file"
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=${WEBUI_PORT}
    volumes:
      - ./qbittorrent/config:/config
      - ./qbittorrent/downloads:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    networks:
      - proxy
      - proton-connect
    labels:
      - "traefik.docker.network=proxy"
      - "traefik.enable=true"
      - "traefik.http.services.qbittorrent.loadbalancer.server.port=8080"
      - "traefik.http.routers.qbittorrent.entrypoints=https"
      - "traefik.http.routers.qbittorrent.rule=Host(`${TRAEFIK_QBIT}`)"
      - "traefik.http.routers.qbittorrent.tls=true"
      - "traefik.http.routers.qbittorrent.tls.certresolver=mydnschallenge"
      # Watchtower Update
      - "com.centurylinklabs.watchtower.enable=true"
      # Ip filtering
      #- "traefik.http.routers.qbittorrent.middlewares=whitelist@file"

    restart: unless-stopped

networks:
  proxy:
    external: true
    name: proxy

  proton-connect:` 

My proton-privoxy container logs:
`$ docker logs proton-privoxy
Connecting to US-VA#38 via UDP...
Connected!
2023-05-16 14:05:42.707 7fec29c62b48 Info: Privoxy version 3.0.33
2023-05-16 14:05:42.707 7fec29c62b48 Info: Program name: privoxy
2023-05-16 14:05:42.707 7fec29c62b48 Info: Listening on port 8080 on IP address 0.0.0.0
`

I even tried port forwarding the privoxy container in my router with the ip of the host pc and the containers port.

**Comment by walterl** [comment]
Since your test `curl` command is returning a VPN IP as expected, your issue probably lies outside the scope of proton-privoxy.

AFAIK Privoxy only supports HTTP traffic, so it might not be feasible to use it for BitTorrent.
