### ISSUE TITLE
How can I run 2 or more instances?

### ISSUE THREAD

**Issue by Mevatlave-Kraspek** [walterl/proton-privoxy#33]
Hi,

thanks for this great project.

How Can I run 2 container or more of the built docker image?

I tried on host:

     mknod /dev/net/tun2 c 10 200
     ip tuntap add mode tap tap2

Changed `/dev/net/tun` to `/dev/net/tun2` in the `docker run` command, changed ports, but there's only one container at the same time allowed.

Any hint?

**Comment by Mevatlave-Kraspek** [comment]
diff -ruN ../proton-privoxy/app/proton-privoxy/config ./app/proton-privoxy/config
    --- ../proton-privoxy/app/proton-privoxy/config	2023-05-21 20:02:55.573317437 +0200
    +++ ./app/proton-privoxy/config	2023-05-22 22:29:34.442038886 +0200
    @@ -1,6 +1,6 @@
     confdir /app/proton-privoxy
     logdir /var/log/privoxy
    -listen-address  0.0.0.0:8080
    +listen-address  0.0.0.0:8081
     
     #debug   1    # show each GET/POST/CONNECT request
     debug   4096 # Startup banner and warnings
    diff -ruN ../proton-privoxy/app/proton-privoxy/run ./app/proton-privoxy/run
    --- ../proton-privoxy/app/proton-privoxy/run	2023-05-21 20:02:55.573317437 +0200
    +++ ./app/proton-privoxy/run	2023-05-26 01:14:53.302706581 +0200
    @@ -2,13 +2,13 @@
     
     # Create the necessary file structure for /dev/net/tun
     # required to run on docker swarm, as there are no devices available
    -if ( [ ! -c /dev/net/tun ] ); then
    +if ( [ ! -c /dev/net/tun2 ] ); then
       if ( [ ! -d /dev/net ] ); then
         mkdir -m 755 /dev/net
       fi
    -  mknod /dev/net/tun c 10 200
    -  chmod 0755 /dev/net/tun
    -  echo "Created /dev/net/tun."
    +  mknod /dev/net/tun2 c 10 200
    +  chmod 0755 /dev/net/tun2
    +  echo "Created /dev/net/tun2."
     fi
     
     PVDIR=/root/.pvpn-cli
    diff -ruN ../proton-privoxy/connect.ovpn ./connect.ovpn
    --- ../proton-privoxy/connect.ovpn	2023-05-21 20:13:27.115587553 +0200
    +++ ./connect.ovpn	2023-05-26 01:15:10.030700454 +0200
    @@ -1,5 +1,5 @@
     client
    -dev tun
    +dev tun2
     proto udp
     
     remote 146.70.72.130 5060
    diff -ruN ../proton-privoxy/Dockerfile ./Dockerfile
    --- ../proton-privoxy/Dockerfile	2023-05-21 20:11:48.657996307 +0200
    +++ ./Dockerfile	2023-05-22 22:29:34.442038886 +0200
    @@ -3,7 +3,7 @@
     LABEL version="0.4.2"
     # XXX Copy version to Docker image tag in .github/workflows/docker.yml when changing!
     
    -EXPOSE 8080
    +EXPOSE 8081
     
     ENV PVPN_USERNAME= \
         PVPN_USERNAME_FILE= \

    diff -ruN ../proton-privoxy/README.md ./README.md
    --- ../proton-privoxy/README.md	2023-05-21 20:02:55.573317437 +0200
    +++ ./README.md	2023-05-22 22:29:34.442038886 +0200
    @@ -14,7 +14,7 @@
     docker run -d \
          --device=/dev/net/tun --cap-add=NET_ADMIN \
          -v /etc/localtime:/etc/localtime:ro \
    -     -p 8888:8080 \
    +     -p 9999:8081 \
          -e PVPN_USERNAME=my_protonvpn_openvpn_username \
          -e PVPN_PASSWORD=my_protonvpn_openvpn_password \
          --name proton-privoxy walt3rl/proton-privoxy
    @@ -35,7 +35,7 @@
         volumes:
           - /etc/localtime:/etc/localtime:ro
         ports:
    -      - 8888:8080
    +      - 9999:8081
         restart: unless-stopped
         devices:
           - /dev/net/tun
    @@ -48,12 +48,12 @@
     1. initializes a `protonvpn` CLI configuration
     2. refreshes ProtonVPN server data (connects to https://api.protonvpn.ch)
     3. sets up an OpenVPN connection to ProtonVPN with your ProtonVPN account details, and
    -4. starts a Privoxy server, accessible at http://127.0.0.1:8888, that directs traffic over your VPN connection.
    +4. starts a Privoxy server, accessible at http://127.0.0.1:9999, that directs traffic over your VPN connection.
     
     Test:
     
     ```
    -curl --proxy http://127.0.0.1:8888 https://ipinfo.io/ip
    +curl --proxy http://127.0.0.1:9999 https://ipinfo.io/ip
     ```
    diff -ruN ../proton-privoxy/test/docker_secrets_test/docker-compose.yml ./test/docker_secrets_test/docker-compose.yml
    --- ../proton-privoxy/test/docker_secrets_test/docker-compose.yml	2023-05-21 20:02:55.577317339 +0200
    +++ ./test/docker_secrets_test/docker-compose.yml	2023-05-22 22:29:34.442038886 +0200
    @@ -10,7 +10,7 @@
           - /etc/localtime:/etc/localtime:ro
           - .:/test
         ports:
    -      - 8888:8080
    +      - 9999:8081
         restart: unless-stopped
         devices:
           - /dev/net/tun


But I get issue:

    curl --proxy 127.0.0.1:9999 https://ifconfig.me/ip
    curl: (56) Proxy CONNECT aborted

**Comment by Mevatlave-Kraspek** [comment]
# cp -a /dev/net/tun /dev/net/tun2

**Comment by walterl** [comment]
I would just run multiple containers with different configs.
