### ISSUE TITLE
Privoxy web interface not working

### ISSUE THREAD

**Issue by ProgramComputer** [walterl/proton-privoxy#9]
https://www.privoxy.org/user-manual/configuration.html

 http://p.p/ shows 500 error 

> 500 Internal Privoxy Error
> Privoxy encountered an error while processing your request:
> 
> Could not load template file default or one of its included components.
> 
> Please contact your proxy administrator.
> 
> If you are the proxy administrator, please put the required file(s)in the (confdir)/templates directory. The location of the (confdir) directory is specified in the main Privoxy config file. (It's typically the Privoxy install directory, or /etc/privoxy/).

**Comment by walterl** [comment]
Fixed in e1bc3f7. Thanks for the report. :+1:

**Comment by walterl** [comment]
I'm going through all open issues and PRs. Once I'm done, I'll deploy all new fixes (including this one) to Dockerhub as version 0.4.

**Comment by walterl** [comment]
Pushed version 0.4 to Docker Hub.
